BEGIN;

-- =============================================
-- TABLAS PARA TEST CAAS (ESCALA 1-5)
-- Escala de Adaptabilidad a la Carrera
-- =============================================

-- 1) Tabla de preguntas cerradas CAAS (Likert 1-5)
CREATE TABLE IF NOT EXISTS caas_questions (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id      integer NOT NULL REFERENCES tests(id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
  external_id  integer NOT NULL,
  text         text NOT NULL,
  dimension    varchar(50) NOT NULL,
  order_index  integer NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_caas_questions_test_external
    UNIQUE (test_id, external_id),

  CONSTRAINT caas_questions_dimension_check
    CHECK (dimension IN ('preocupacion', 'control', 'curiosidad', 'confianza'))
);

CREATE INDEX idx_caas_questions_test ON caas_questions (test_id);
CREATE INDEX idx_caas_questions_dimension ON caas_questions (dimension);

-- 2) Tabla de respuestas cerradas CAAS (escala 1-5)
CREATE TABLE IF NOT EXISTS caas_answers (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id  integer NOT NULL REFERENCES attempts(id)
               ON UPDATE CASCADE ON DELETE CASCADE,
  question_id integer NOT NULL REFERENCES caas_questions(id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
  value       integer NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_caas_answers_attempt_question
    UNIQUE (attempt_id, question_id),

  CONSTRAINT caas_answers_value_range
    CHECK (value >= 1 AND value <= 5)
);

CREATE INDEX idx_caas_answers_attempt ON caas_answers (attempt_id);

-- 3) Tabla de respuestas abiertas CAAS
CREATE TABLE IF NOT EXISTS caas_open_answers (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id   integer NOT NULL REFERENCES attempts(id)
               ON UPDATE CASCADE ON DELETE CASCADE,
  question_key varchar(50) NOT NULL,
  answer_text  text NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_caas_open_answers_attempt_key
    UNIQUE (attempt_id, question_key)
);

CREATE INDEX idx_caas_open_answers_attempt ON caas_open_answers (attempt_id);

-- 4) Tabla de resultados CAAS
CREATE TABLE IF NOT EXISTS caas_results (
  id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id              integer NOT NULL REFERENCES attempts(id)
                           ON UPDATE CASCADE ON DELETE CASCADE,
  total_score             integer NOT NULL,
  max_score               integer NOT NULL,
  percentage              numeric(5,2) NOT NULL,
  scores_by_dimension     jsonb NOT NULL,
  level                   varchar(20) NULL,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_caas_results_attempt
    UNIQUE (attempt_id),

  CONSTRAINT caas_results_percentage_range
    CHECK (percentage >= 0 AND percentage <= 100),

  CONSTRAINT caas_results_level_check
    CHECK (level IS NULL OR level IN ('bajo', 'medio', 'alto'))
);

CREATE INDEX idx_caas_results_attempt ON caas_results (attempt_id);

COMMIT;
