-- Creación de las tablas
BEGIN;

-- 1) Proceso/Año
CREATE TABLE IF NOT EXISTS admission_process (
  admission_process_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  year SMALLINT NOT NULL UNIQUE
);

-- 2) Dimensiones
CREATE TABLE IF NOT EXISTS institution (
  institution_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_pace BOOLEAN NOT NULL DEFAULT FALSE,
  has_gratuity BOOLEAN NOT NULL DEFAULT FALSE,
  url TEXT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS location (
  location_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS career (
  career_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- 3) Oferta DEMRE por año + código (PK compuesta)
CREATE TABLE IF NOT EXISTS program_offer (
  admission_process_id INTEGER NOT NULL REFERENCES admission_process(admission_process_id) ON DELETE CASCADE,
  demre_code INTEGER NOT NULL,

  institution_id INTEGER NOT NULL REFERENCES institution(institution_id) ON DELETE RESTRICT,
  location_id INTEGER NOT NULL REFERENCES location(location_id) ON DELETE RESTRICT,
  career_id INTEGER NOT NULL REFERENCES career(career_id) ON DELETE RESTRICT,

  -- mínimos
  min_pond NUMERIC(6,2),
  min_prom_pond NUMERIC(6,2),

  -- puntaje de corte (1 por año)
  cut_score NUMERIC(6,2),

  -- pruebas especiales
  has_special_test BOOLEAN NOT NULL DEFAULT FALSE,
  has_special_peda BOOLEAN NOT NULL DEFAULT FALSE,

  raw_row JSONB,

  PRIMARY KEY (admission_process_id, demre_code)
);

-- 4) Componentes y ponderaciones (por año)
CREATE TABLE IF NOT EXISTS component (
  component_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,   -- NEM, RANKING, CL, M1, HIST, CIEN, M2, ASIG_PED
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS offer_component_weight (
  admission_process_id INTEGER NOT NULL,
  demre_code INTEGER NOT NULL,
  component_id INTEGER NOT NULL REFERENCES component(component_id) ON DELETE RESTRICT,
  weight_percent NUMERIC(5,2) NOT NULL,

  PRIMARY KEY (admission_process_id, demre_code, component_id),
  FOREIGN KEY (admission_process_id, demre_code)
    REFERENCES program_offer(admission_process_id, demre_code)
    ON DELETE CASCADE
);

-- 5) Semestre de ingreso (ALL/S1/S2)
CREATE TABLE IF NOT EXISTS intake (
  intake_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,   -- ALL, S1, S2
  name TEXT NOT NULL
);

-- 6) Tipos de cupo (REGULAR/MC/BEA/PACE)
CREATE TABLE IF NOT EXISTS quota_type (
  quota_type_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS offer_quota (
  offer_quota_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  admission_process_id INTEGER NOT NULL,
  demre_code INTEGER NOT NULL,

  quota_type_id INTEGER NOT NULL REFERENCES quota_type(quota_type_id) ON DELETE RESTRICT,
  intake_id INTEGER NOT NULL REFERENCES intake(intake_id) ON DELETE RESTRICT,
  quota_value INTEGER NOT NULL,

  UNIQUE (admission_process_id, demre_code, quota_type_id, intake_id),
  FOREIGN KEY (admission_process_id, demre_code)
    REFERENCES program_offer(admission_process_id, demre_code)
    ON DELETE CASCADE
);

-- Índices útiles para filtros
CREATE INDEX IF NOT EXISTS idx_offer_process ON program_offer(admission_process_id);
CREATE INDEX IF NOT EXISTS idx_offer_inst ON program_offer(institution_id);
CREATE INDEX IF NOT EXISTS idx_offer_loc ON program_offer(location_id);
CREATE INDEX IF NOT EXISTS idx_offer_career ON program_offer(career_id);
CREATE INDEX IF NOT EXISTS idx_offer_cut_score ON program_offer(cut_score);

CREATE INDEX IF NOT EXISTS idx_weight_component_value
  ON offer_component_weight(component_id, weight_percent);

COMMIT;

-- Seed básico (ejecutar una vez)
INSERT INTO intake (code, name) VALUES
('ALL','Todos'),
('S1','1er semestre'),
('S2','2do semestre')
ON CONFLICT (code) DO NOTHING;

INSERT INTO quota_type (code, name) VALUES
('REGULAR','Cupos regulares'),
('MC','Más Mujeres en Ciencias'),
('BEA','Beca Excelencia Académica'),
('PACE','Cupos PACE')
ON CONFLICT (code) DO NOTHING;

INSERT INTO component (code, name) VALUES
('NEM','NEM'),
('RANKING','Ranking'),
('CL','Competencia Lectora'),
('M1','Matemática 1'),
('HIST','Historia'),
('CIEN','Ciencias'),
('M2','Matemática 2')
ON CONFLICT (code) DO NOTHING;

-- ? Creación de la vista para el front
DROP VIEW IF EXISTS v_offers_flat CASCADE;

CREATE OR REPLACE VIEW v_offers_flat AS
WITH quota_pivot AS (
  SELECT
    oq.admission_process_id,
    oq.demre_code,

    MAX(CASE WHEN qt.code='REGULAR' AND it.code='ALL' THEN oq.quota_value END) AS quota_all,
    MAX(CASE WHEN qt.code='REGULAR' AND it.code='S1'  THEN oq.quota_value END) AS quota_s1,
    MAX(CASE WHEN qt.code='REGULAR' AND it.code='S2'  THEN oq.quota_value END) AS quota_s2,

    MAX(CASE WHEN qt.code='MC'   AND it.code='ALL' THEN oq.quota_value END) AS quota_mc,
    MAX(CASE WHEN qt.code='BEA'  AND it.code='ALL' THEN oq.quota_value END) AS quota_bea,
    MAX(CASE WHEN qt.code='PACE' AND it.code='ALL' THEN oq.quota_value END) AS quota_pace
  FROM offer_quota oq
  JOIN quota_type qt ON qt.quota_type_id = oq.quota_type_id
  JOIN intake it ON it.intake_id = oq.intake_id
  GROUP BY oq.admission_process_id, oq.demre_code
),
weight_pivot AS (
  SELECT
    ow.admission_process_id,
    ow.demre_code,

    MAX(CASE WHEN comp.code='NEM'     THEN ow.weight_percent END) AS nem,
    MAX(CASE WHEN comp.code='RANKING' THEN ow.weight_percent END) AS ranking,
    MAX(CASE WHEN comp.code='CL'      THEN ow.weight_percent END) AS cl,
    MAX(CASE WHEN comp.code='M1'      THEN ow.weight_percent END) AS m1,
    MAX(CASE WHEN comp.code='HIST'    THEN ow.weight_percent END) AS historia,
    MAX(CASE WHEN comp.code='CIEN'    THEN ow.weight_percent END) AS ciencias,
    MAX(CASE WHEN comp.code='M2'      THEN ow.weight_percent END) AS m2
  FROM offer_component_weight ow
  JOIN component comp ON comp.component_id = ow.component_id
  GROUP BY ow.admission_process_id, ow.demre_code
)
SELECT
  -- PK para Sequelize
  (ap.year::text || '-' || po.demre_code::text) AS offer_key,

  ap.year,
  po.demre_code,

  po.institution_id,
  i.name AS institution_name,
  i.is_pace AS institution_is_pace,
  i.has_gratuity AS institution_has_gratuity,
  i.url AS institution_url,

  po.career_id,
  c.name AS career,

  po.location_id,
  l.name AS location_name,

  po.min_pond,
  po.min_prom_pond,
  po.cut_score,

  po.has_special_test,
  po.has_special_peda,

  qp.quota_all,
  qp.quota_s1,
  qp.quota_s2,
  qp.quota_mc,
  qp.quota_bea,
  qp.quota_pace,

  wp.nem,
  wp.ranking,
  wp.cl,
  wp.m1,
  wp.historia,
  wp.ciencias,
  wp.m2

FROM program_offer po
JOIN admission_process ap
  ON ap.admission_process_id = po.admission_process_id
JOIN institution i
  ON i.institution_id = po.institution_id
JOIN career c
  ON c.career_id = po.career_id
JOIN location l
  ON l.location_id = po.location_id
LEFT JOIN quota_pivot qp
  ON qp.admission_process_id = po.admission_process_id
 AND qp.demre_code = po.demre_code
LEFT JOIN weight_pivot wp
  ON wp.admission_process_id = po.admission_process_id
 AND wp.demre_code = po.demre_code;

-- ? Tests para detectar carga
-- ofertas
SELECT COUNT(*) FROM program_offer;

-- ponderaciones
SELECT COUNT(*) FROM offer_component_weight;

-- cupos
SELECT COUNT(*) FROM offer_quota;

-- sanity: años cargados
SELECT year FROM admission_process ORDER BY year;

-- probar vista (después de crearla)
SELECT offer_key, year, demre_code, career, location_name, cut_score
FROM v_offers_flat
LIMIT 10;