BEGIN;

-- =========================
-- 0) DROP en orden seguro
-- =========================
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS inap_results CASCADE;
DROP TABLE IF EXISTS attempts CASCADE;
DROP TABLE IF EXISTS student_profiles CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS paes_score_records CASCADE;
DROP TABLE IF EXISTS periods CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS nem_conversions CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;

-- =========================
-- 1) TABLAS BASE
-- =========================

-- organizations
CREATE TABLE organizations (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       varchar(180) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- tests
CREATE TABLE tests (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key        varchar(40)  NOT NULL,
  version    varchar(20)  NOT NULL,
  name       varchar(120) NOT NULL,
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- users
CREATE TABLE users (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id      integer NOT NULL REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  rut                  varchar(20)  NOT NULL,
  role                 text NOT NULL,
  name                 varchar(120) NOT NULL,
  email                varchar(180) NOT NULL,
  password_hash        varchar(255) NOT NULL,
  must_change_password boolean NOT NULL DEFAULT false,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT users_rut_unique   UNIQUE (rut),
  CONSTRAINT users_email_unique UNIQUE (email),

  -- Enum flexible: UserRole = ('admin','student')
  CONSTRAINT users_role_check CHECK (role IN ('admin','student'))
);

CREATE INDEX idx_users_rut  ON users (rut);
CREATE INDEX idx_users_role ON users (role);

-- =========================
-- 2) PERIODS / ENROLLMENTS / STUDENT_PROFILES
-- =========================

-- periods
CREATE TABLE periods (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id integer NOT NULL REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  test_id         integer NOT NULL REFERENCES tests(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  name            varchar(200) NOT NULL,
  status          text NOT NULL DEFAULT 'draft',
  start_at        timestamptz NULL,
  end_at          timestamptz NULL,
  settings        json NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  -- Enum flexible: PeriodStatus = ('draft','active','closed')
  CONSTRAINT periods_status_check CHECK (status IN ('draft','active','closed'))
);

CREATE INDEX idx_periods_org    ON periods (organization_id);
CREATE INDEX idx_periods_test   ON periods (test_id);
CREATE INDEX idx_periods_status ON periods (status);

-- enrollments
CREATE TABLE enrollments (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id       integer NOT NULL REFERENCES periods(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  student_user_id integer NOT NULL REFERENCES users(id)   ON UPDATE CASCADE ON DELETE RESTRICT,
  status          text NOT NULL DEFAULT 'active',
  meta            json NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_period_student UNIQUE (period_id, student_user_id),

  -- Enum flexible: EnrollmentStatus = ('invited','active','completed','removed')
  CONSTRAINT enrollments_status_check CHECK (status IN ('invited','active','completed','removed'))
);

CREATE INDEX idx_enrollments_period  ON enrollments (period_id);
CREATE INDEX idx_enrollments_student ON enrollments (student_user_id);

-- student_profiles (PK = user_id)
CREATE TABLE student_profiles (
  user_id        integer PRIMARY KEY REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  education_type text NOT NULL,
  nem_avg        numeric(3,2) NOT NULL,
  nem_score      integer NOT NULL,
  ranking_score  integer NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),

  -- Enum flexible: EducationType (según tu modelo StudentProfile) = ('ch','ch_adultos','tp')
  CONSTRAINT student_profiles_education_type_check CHECK (education_type IN ('hc','hc_adults','tp'))
);

CREATE INDEX idx_student_profiles_education_type ON student_profiles (education_type);

-- =========================
-- 3) INAP QUESTIONS / ATTEMPTS / INAP ANSWERS / INAP RESULTS
-- =========================

-- inap_questions
CREATE TABLE inap_questions (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id      integer NOT NULL REFERENCES tests(id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
  external_id  integer NOT NULL,
  text         text NOT NULL,
  area         varchar(10) NOT NULL,
  dim          text[] NOT NULL DEFAULT '{}'::text[],
  order_index  integer NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_inap_questions_test_external
    UNIQUE (test_id, external_id)
);

CREATE INDEX idx_inap_questions_test ON inap_questions (test_id);


-- attempts (genérico)
CREATE TABLE attempts (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        integer NOT NULL REFERENCES users(id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
  period_id      integer NOT NULL REFERENCES periods(id)
                 ON UPDATE CASCADE ON DELETE RESTRICT,
  status         text NOT NULL DEFAULT 'in_progress',
  answered_count integer NOT NULL DEFAULT 0,
  finished_at    timestamptz NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_attempts_period_user
    UNIQUE (period_id, user_id),

  CONSTRAINT attempts_status_check
    CHECK (status IN ('in_progress','finished'))
);

CREATE INDEX idx_attempts_user ON attempts (user_id);
CREATE INDEX idx_attempts_period ON attempts (period_id);


-- inap_answers
CREATE TABLE inap_answers (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id  integer NOT NULL REFERENCES attempts(id)
               ON UPDATE CASCADE ON DELETE CASCADE,
  question_id integer NOT NULL REFERENCES inap_questions(id)
               ON UPDATE CASCADE ON DELETE RESTRICT,
  value       boolean NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_inap_answers_attempt_question
    UNIQUE (attempt_id, question_id)
);

CREATE INDEX idx_inap_answers_attempt ON inap_answers (attempt_id);


-- inap_results
CREATE TABLE inap_results (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id          integer NOT NULL REFERENCES attempts(id)
                       ON UPDATE CASCADE ON DELETE CASCADE,
  scores_by_area_dim  jsonb NOT NULL,
  max_by_area_dim     jsonb NOT NULL,
  percent_by_area_dim jsonb NOT NULL,
  top_areas_by_interes jsonb NOT NULL,
  top_areas_by_aptitud jsonb NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uniq_inap_results_attempt
    UNIQUE (attempt_id)
);

CREATE INDEX idx_inap_results_attempt ON inap_results (attempt_id);


-- =========================
-- 4) PAES SCORE RECORDS / NEM CONVERSIONS
-- =========================

-- paes_score_records
CREATE TABLE paes_score_records (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_user_id integer NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  name            varchar(120) NOT NULL,
  notes           varchar(500) NULL,
  taken_at        timestamptz NULL,
  cl              integer NULL,
  m1              integer NULL,
  m2              integer NULL,
  ciencias        integer NULL,
  historia        integer NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_paes_score_records_student ON paes_score_records (student_user_id);

-- nem_conversions
CREATE TABLE nem_conversions (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  education_type text NOT NULL,
  nem_avg        numeric(3,2) NOT NULL,
  nem_score      integer NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),

  -- Enum flexible: (según tu modelo NemConversion) = ('hc','hc_adults','tp')
  CONSTRAINT nem_conversions_education_type_check CHECK (education_type IN ('hc','hc_adults','tp'))
);

CREATE INDEX idx_nem_conversions_lookup ON nem_conversions (education_type, nem_avg);

COMMIT;
